\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage{graphicx}

\title{Informe técnico del proyecto Gapminder}
\author{Natalia}
\date{\today}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

\section{Introducción}

Este informe resume los principales resultados del proyecto de Ciencia de Datos realizado con datos de Gapminder.

\section{Objetivos}

El objetivo principal del proyecto es analizar de forma visual la relación entre distintos indicadores socioeconómicos, demográficos y sanitarios de varios países.

\end{document} 

